Add MohistUpdater
HSGamer/MCServerUpdater pull request #24
Opened 2024-09-22 12:35 UTC by Minionguyjpro

This PR adds Mohist to the server updater. I had to tinker a lot around with this but it finally seems to do everything properly when downloading. The API was very different from all the others.

2024-09-22 13:15 UTC, HSGamer requested changes

2024-09-22 13:15 UTC, HSGamer commented on lib/src/main/java/me/hsgamer/mcserverupdater/updater/MohistUpdater.java
> +        }
Where is it used?

2024-09-22 16:58 UTC, Minionguyjpro commented on lib/src/main/java/me/hsgamer/mcserverupdater/updater/MohistUpdater.java
> +        }
It loads the getDownload() function which will do the stuff to get the JSON data. fileMd5 is for the MD5 checksum provided by the JSON of the API and originUrl is basically the URL to the download. Now that I see it, the originUrl doesn't have to be specified.

2024-09-22 17:02 UTC, Minionguyjpro commented on lib/src/main/java/me/hsgamer/mcserverupdater/updater/MohistUpdater.java
> +        }
I have removed the fileName stuff now since it's not necessary.

2024-09-23 10:37 UTC, HSGamer approved these changes

2024-09-23 10:38 UTC, merged